/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { ActTension } from "./actTension";

export interface Act {
  name: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  beatRange: number[];
  tension: ActTension;
  anchor: string;
}
