/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { BeatBridgeStatus } from "./beatBridgeStatus";

/**
 * Editorial metadata present only on auto-inserted bridge beats.
 */
export type BeatBridge = {
  status?: BeatBridgeStatus;
  leftSpoke?: number;
  rightSpoke?: number;
  leftPrompt?: string;
  rightPrompt?: string;
  pairKappa?: number;
};
