/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { BeatBridge } from "./beatBridge";
import type { SonataSection } from "./sonataSection";

/**
 * A single cinematic unit in the reel arc. Maps to one Veo clip. Spoke position (0-23) on the 24-spoke icositetragon determines the Ψ-target, gamma, and phi GOS constants for this beat.

 */
export interface Beat {
  /**
   * 1-based icositetragon spoke label.
   * @minimum 1
   * @maximum 24
   */
  index: number;
  /**
   * 0-based spoke position (0..23).
   * @minimum 0
   * @maximum 23
   */
  spoke: number;
  /**
   * Cinematic visual prompt sent to Veo.
   * @maxLength 600
   */
  visualPrompt: string;
  /** Ψ coherence target for this spoke (A × N). */
  psiTarget: number;
  /** Aesthetic amplitude (real component of Ψ). */
  A: number;
  /** Narrative weight (imaginary component of Ψ). */
  N: number;
  /** Critical line σ = 0.5 (Riemann anchor, constant). */
  sigma: number;
  /** Imaginary Riemann part: 14.134725 + spoke × 0.5. */
  gamma: number;
  /** Angular position: (spoke/24) × 2π × φ. */
  phi: number;
  /**
   * Per-beat clip duration override. Bridge beats default to 1–2s.
   * @minimum 1
   * @maximum 20
   */
  durationSeconds?: number;
  sonataSection?: SonataSection;
  /** Editorial metadata present only on auto-inserted bridge beats. */
  bridge?: BeatBridge;
}
