/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { ClipResultStatus } from "./clipResultStatus";
import type { ContinuityAnalysis } from "./continuityAnalysis";
import type { PsiScore } from "./psiScore";

export interface ClipResult {
  status: ClipResultStatus;
  /** Base64-encoded MP4 clip. */
  video: string;
  videoMimeType: string;
  model: string;
  tier: string;
  appliedDurationSeconds: number;
  appliedAspectRatio: string;
  psiScore: PsiScore;
  continuity?: ContinuityAnalysis;
  /** Base64 PNG of the last frame. Feed into next beat's prevFrame. */
  terminalFrame: string;
  /** The enriched prompt actually sent to Veo (after continuity keywords injected). */
  promptUsed: string;
  /** Server-side cache ID. Pass in /reel/stitch clipIds[] to avoid re-uploading large base64 payloads.
   */
  clipId?: string;
}
