/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */

export type CoherenceReportEmbeddingMode =
  (typeof CoherenceReportEmbeddingMode)[keyof typeof CoherenceReportEmbeddingMode];

export const CoherenceReportEmbeddingMode = {
  hall: "hall",
  raw: "raw",
} as const;
