/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { BridgeFault } from "./bridgeFault";
import type { CoherenceReportEmbeddingMode } from "./coherenceReportEmbeddingMode";

/**
 * Hall-regularised narrative coherence metrics. κ_H (kappaHall) is the primary health indicator — must be < 65.18.

 */
export interface CoherenceReport {
  /** Raw condition number κ(G) of the full Gram matrix. */
  kappa: number;
  /** Hall-regularised condition number κ_H (G + η·I). The key metric. */
  kappaHall: number;
  /** Fault threshold = 65.18. kappaHall < kappaMax = healthy arc. */
  kappaMax: number;
  /** Hall regularisation floor η = 0.09. */
  eta: number;
  bridges: BridgeFault[];
  /** Quantum observer coupling — gap between first two eigenvalues of G_H. Higher = tighter conceptual focus across beats.
   */
  observerPresence: number;
  embeddingMode: CoherenceReportEmbeddingMode;
  /** Full N×N Gram matrix G. */
  gram?: number[][];
  /** Hall-regularised N×N Gram matrix G_H. */
  gramHall?: number[][];
}
