/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { ReelDreamBodyKimaPulse } from "./reelDreamBodyKimaPulse";
import type { Tier } from "./tier";

export type ReelDreamBody = {
  phaseName?: string;
  phaseGene?: string;
  phaseHz?: number;
  /**
   * @minimum 0
   * @maximum 5
   */
  phaseIndex?: number;
  phaseFn?: string;
  /** GOS fundamental κ = 4/π. */
  kappa?: number;
  tier?: Tier;
  /**
   * Previous dream frame's prompt for narrative chaining.
   * @maxLength 300
   */
  memory?: string;
  /** Live Kima Network mainnet telemetry (optional). */
  kimaPulse?: ReelDreamBodyKimaPulse;
};
