/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { TtsVoice } from "./ttsVoice";

export type ReelScoreBodyNarrationItem = {
  /** @maxLength 1000 */
  text: string;
  voice?: TtsVoice;
  /**
   * Onset time in the stitched video. Snap to beatOnsets.
   * @minimum 0
   */
  offsetSeconds: number;
  /** Beat array index (informational, returned in response). */
  beatIndex?: number;
};
