/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { ReelClipStatus500Status } from "./reelClipStatus500Status";

export type ReelClipStatus500 = {
  status: ReelClipStatus500Status;
  error: string;
};
