/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */

export type ReelClipStatus500Status =
  (typeof ReelClipStatus500Status)[keyof typeof ReelClipStatus500Status];

export const ReelClipStatus500Status = {
  error: "error",
} as const;
