/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { ReelImagineBodyAnchorsItem } from "./reelImagineBodyAnchorsItem";
import type { Tier } from "./tier";

export type ReelImagineBody = {
  /** Feed image anchors driving the organism. Up to 8. */
  anchors?: ReelImagineBodyAnchorsItem[];
  /**
   * @minimum 1
   * @maximum 24
   */
  beatCount?: number;
  tier?: Tier;
};
