/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */

/**
 * Live Kima Network mainnet telemetry (optional).
 */
export type ReelDreamBodyKimaPulse = {
  /**
   * Fraction of supply bonded. > 0.72 = HIGH coherence.
   * @minimum 0
   * @maximum 1
   */
  bondedCoherence?: number;
  validatorCount?: number;
  /** uKIMA staked (raw). */
  networkGravity?: number;
  totalSupplyKima?: number;
  bondedTokens?: number;
};
