/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { Beat } from "./beat";
import type { CoherenceReport } from "./coherenceReport";
import type { ReelRepair200IterationsItem } from "./reelRepair200IterationsItem";
import type { ReelRepair200StopReason } from "./reelRepair200StopReason";

export type ReelRepair200 = {
  /** Expanded beat array with bridge beats inserted. */
  beats: Beat[];
  coherence: CoherenceReport;
  iterations: ReelRepair200IterationsItem[];
  stopReason: ReelRepair200StopReason;
  converged: boolean;
  insertedCount: number;
  initialCoherence: CoherenceReport;
};
