/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { BridgeFault } from "./bridgeFault";
import type { ReelRepair200IterationsItemInsertedItem } from "./reelRepair200IterationsItemInsertedItem";

export type ReelRepair200IterationsItem = {
  pass?: number;
  kappa?: number;
  kappaHall?: number;
  bridgesBefore?: BridgeFault[];
  inserted?: ReelRepair200IterationsItemInsertedItem[];
};
