/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { AspectRatio } from "./aspectRatio";
import type { Beat } from "./beat";
import type { Tier } from "./tier";

export type ReelClipBody = {
  beat: Beat;
  /** Base64 PNG of the previous clip's terminal frame. Used to seed visual continuity keywords into the Veo prompt.
   */
  prevFrame?: string;
  tier?: Tier;
  /**
   * @minimum 1
   * @maximum 20
   */
  durationSeconds?: number;
  aspectRatio?: AspectRatio;
  quality?: string;
};
