/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { Tier } from "./tier";

export type ReelOutlineBody = {
  /**
   * The narrative theme or concept for the reel.
   * @maxLength 600
   */
  theme: string;
  /**
   * Number of beats (clips). 24 = full icositetragon.
   * @minimum 1
   * @maximum 24
   */
  beatCount?: number;
  tier?: Tier;
  /** Enforce Sonata form structure: Exposition 25% / Development 50% / Recapitulation 25%. Sets sonataSection on each beat.
   */
  sonataMode?: boolean;
  /**
   * Visual anchor strings from feed images. Folded into the subject anchor and lighting arc by the Architecture HV.

   * @maxItems 8
   */
  referencePrompts?: string[];
};
