/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { ReelScoreBodyMusic } from "./reelScoreBodyMusic";
import type { ReelScoreBodyNarrationItem } from "./reelScoreBodyNarrationItem";
import type { Tier } from "./tier";

export type ReelScoreBody = {
  /** Base64-encoded silent stitched video (MP4 or WebM). */
  video: string;
  videoMimeType?: string;
  narration?: ReelScoreBodyNarrationItem[];
  music?: ReelScoreBodyMusic;
  /**
   * @minimum 0
   * @maximum 2
   */
  narrationVolume?: number;
  tier?: Tier;
};
