/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { ConceptDirection } from "./conceptDirection";

export type ReelImagine200 = {
  /**
   * @minItems 1
   * @maxItems 4
   */
  concepts: ConceptDirection[];
  model: string;
  anchorsUsed: number;
};
