/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */

export type ReelRepair200IterationsItemInsertedItem = {
  atIndex?: number;
  spoke?: number;
  visualPrompt?: string;
  durationSeconds?: number;
  /**
   * @minItems 2
   * @maxItems 2
   */
  betweenSpokes?: number[];
};
