/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { ReelStitch200Coherence } from "./reelStitch200Coherence";
import type { ReelStitch200Resolution } from "./reelStitch200Resolution";

export type ReelStitch200 = {
  /** Base64-encoded stitched MP4. */
  video: string;
  videoMimeType: string;
  /** Total stitched video duration in seconds. */
  durationSeconds: number;
  aspectRatio: string;
  resolution: ReelStitch200Resolution;
  format: string;
  /** Authoritative per-beat onset timestamps (seconds) in the stitched timeline. Account for xfade overlaps and bridge frame durations. Use these — not a naive cumulative sum — for narration offset snapping.
   */
  beatOnsets: number[];
  observerPresence?: number;
  /** Coherence re-check run on the stitched beat sequence. */
  coherence?: ReelStitch200Coherence;
};
