/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { Beat } from "./beat";
import type { Tier } from "./tier";

export type ReelRepairPairBody = {
  left: Beat;
  right: Beat;
  /** @maxLength 600 */
  theme?: string;
  tier?: Tier;
  /** κ value of this pair from the last coherence pass (informational, fed to the HV prompt). */
  pairKappa?: number;
};
