/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */

export type ReelStitchBodyBeatsItem = {
  /**
   * Aesthetic gradient B(t) = max(0, min(1, 1 − |Ψ − 1.0|)).
   * @minimum 0
   * @maximum 1
   */
  B: number;
  /**
   * @minimum 1
   * @maximum 20
   */
  durationSeconds: number;
  visualPrompt: string;
};
