/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { ReelScore200Music } from "./reelScore200Music";
import type { ReelScore200NarrationItem } from "./reelScore200NarrationItem";
import type { ReelScore200TtsErrorsItem } from "./reelScore200TtsErrorsItem";

export type ReelScore200 = {
  /** Base64 mixed video with audio baked in. */
  video: string;
  videoMimeType: string;
  durationSeconds: number;
  narration?: ReelScore200NarrationItem[];
  narrationVolume?: number;
  music?: ReelScore200Music;
  ttsErrors?: ReelScore200TtsErrorsItem[];
};
