/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { ReelDream200GosReading } from "./reelDream200GosReading";

export type ReelDream200 = {
  /** The surreal image prompt generated by the ANUBIS DREAMER. */
  prompt: string;
  /** 4-6 line poem fragment rising from deep generation. */
  echo: string;
  /** Base64-encoded generated image. */
  image: string;
  model: string;
  tier: string;
  gosReading: ReelDream200GosReading;
};
