/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { Tier } from "./tier";
import type { TtsVoice } from "./ttsVoice";

export type ReelNarratePreviewBody = {
  /** @maxLength 1000 */
  text: string;
  voice?: TtsVoice;
  tier?: Tier;
};
