/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { Beat } from "./beat";
import type { Tier } from "./tier";

export type ReelRepairBody = {
  /** @minItems 2 */
  beats: Beat[];
  /** @maxLength 600 */
  theme?: string;
  tier?: Tier;
  /**
   * @minimum 1
   * @maximum 6
   */
  maxIterations?: number;
};
