/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */

export type ReelStitch200CoherenceBridgesRenderedItem = {
  from?: number;
  to?: number;
  durationSeconds?: number;
  transition?: string;
  /** Hex colour of the palette-derived bridge frame. */
  color?: string;
};
