/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { AspectRatio } from "./aspectRatio";
import type { ReelStitchBodyBeatsItem } from "./reelStitchBodyBeatsItem";

export type ReelStitchBody = {
  /** Base64 MP4 clips (legacy / cache-miss fallback). */
  clips?: string[];
  /** Server-side clip cache IDs from ClipResult.clipId. Preferred over clips — avoids large request bodies.
   */
  clipIds?: string[];
  /** @minItems 1 */
  beats: ReelStitchBodyBeatsItem[];
  aspectRatio?: AspectRatio;
};
