/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { ConceptDirection } from "./conceptDirection";
import type { ReelImagineRefineBodyAnchorsItem } from "./reelImagineRefineBodyAnchorsItem";
import type { Tier } from "./tier";

export type ReelImagineRefineBody = {
  concept: ConceptDirection;
  anchors?: ReelImagineRefineBodyAnchorsItem[];
  beatCount?: number;
  tier?: Tier;
};
