/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */

export type ReelScoreBodyMusic = {
  /** Base64 audio track (MP3, WAV, OGG, AAC, FLAC, M4A). */
  audio: string;
  mimeType: string;
  /**
   * @minimum 0
   * @maximum 2
   */
  volume?: number;
};
