/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { CoherenceReport } from "./coherenceReport";

export type ReelCoherence200 = {
  coherence: CoherenceReport;
};
