/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { ClipResult } from "./clipResult";

export type ReelClipStatus200 =
  | {
      status: "pending" | "running";
    }
  | ClipResult;
