/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */
import type { ArchResult } from "./archResult";
import type { Beat } from "./beat";
import type { CoherenceReport } from "./coherenceReport";

export type ReelOutline200 = {
  /**
   * AI-generated or theme-derived working title.
   * @maxLength 80
   */
  title: string;
  theme: string;
  sonataMode: boolean;
  beats: Beat[];
  coherence: CoherenceReport;
  model: string;
  tier: string;
  arch: ArchResult;
};
