/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Ω-GRAM / Ω-REEL API — autonomous cinematic content engine
 * OpenAPI spec version: 0.1.0
 */

export type SonataSection = (typeof SonataSection)[keyof typeof SonataSection];

export const SonataSection = {
  exposition: "exposition",
  development: "development",
  recapitulation: "recapitulation",
} as const;
