/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * KAPPA Heartbeat Tracker API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export type RegisterDeviceBodyMetadata = { [key: string]: unknown };

export interface RegisterDeviceBody {
  deviceId: string;
  name: string;
  type: string;
  os: string;
  capabilities?: string[];
  metadata?: RegisterDeviceBodyMetadata;
}

export interface DeviceInfo {
  id: string;
  deviceId: string;
  name: string;
  type: string;
  os: string;
  online: boolean;
  /** @nullable */
  ip?: string | null;
  capabilities: string[];
  registeredAt: string;
  /** @nullable */
  lastHeartbeat?: string | null;
  /** @nullable */
  lastDisconnect?: string | null;
}

export type DeviceDetailMetadata = { [key: string]: unknown };

export type HeartbeatRecordMetadata = { [key: string]: unknown };

export interface HeartbeatRecord {
  id: string;
  deviceId: string;
  timestamp: string;
  /** @nullable */
  latencyMs?: number | null;
  metadata: HeartbeatRecordMetadata;
}

export type AlertMetadata = { [key: string]: unknown };

export interface Alert {
  id: string;
  deviceId: string;
  type: string;
  message: string;
  severity: number;
  metadata: AlertMetadata;
  createdAt: string;
  acknowledged: boolean;
}

export interface DeviceDetail {
  id: string;
  deviceId: string;
  name: string;
  type: string;
  os: string;
  online: boolean;
  /** @nullable */
  ip?: string | null;
  capabilities: string[];
  metadata: DeviceDetailMetadata;
  registeredAt: string;
  /** @nullable */
  lastHeartbeat?: string | null;
  /** @nullable */
  lastDisconnect?: string | null;
  recentHeartbeats: HeartbeatRecord[];
  activeAlerts: Alert[];
}

export type DeviceStatsByType = {
  pc: number;
  phone: number;
  sensor: number;
  iot: number;
};

export interface DeviceStats {
  total: number;
  online: number;
  offline: number;
  byType: DeviceStatsByType;
  uptimePercent24h: number;
}

export type HeartbeatBodyMetadata = { [key: string]: unknown };

export interface HeartbeatBody {
  deviceId: string;
  metadata?: HeartbeatBodyMetadata;
}

export interface HeartbeatAck {
  ack: boolean;
  serverTime: number;
  nextExpectedMs: number;
}

export type IngestSensorsBodyReadingsItemValues = { [key: string]: unknown };

export type IngestSensorsBodyReadingsItem = {
  sensorType: string;
  timestamp: number;
  values: IngestSensorsBodyReadingsItemValues;
};

export interface IngestSensorsBody {
  deviceId: string;
  readings: IngestSensorsBodyReadingsItem[];
}

export type SensorReadingValues = { [key: string]: unknown };

export interface SensorReading {
  id: string;
  deviceId: string;
  sensorType: string;
  timestamp: string;
  values: SensorReadingValues;
}

export type KappaStatusRecentHeartbeatsMetadata = { [key: string]: unknown };

export type KappaStatusRecentHeartbeats = {
  [key: string]: {
    lastSeen: string;
    /** @nullable */
    latencyMs?: number | null;
    metadata: KappaStatusRecentHeartbeatsMetadata;
  };
};

export interface KappaStatus {
  devices: DeviceInfo[];
  onlineCount: number;
  alerts: Alert[];
  recentHeartbeats: KappaStatusRecentHeartbeats;
  serverUptime: number;
}

export type CommandBodyArgs = { [key: string]: unknown };

export interface CommandBody {
  deviceId: string;
  command: string;
  args?: CommandBodyArgs;
}

export type ListDevicesParams = {
  type?: string;
  online?: boolean;
};

export type DeleteDevice200 = {
  deleted: boolean;
};

export type GetHeartbeatHistoryParams = {
  hours?: number;
  limit?: number;
};

export type IngestSensors200 = {
  ingested: number;
};

export type GetSensorReadingsParams = {
  type?: string;
  hours?: number;
  limit?: number;
};

export type GetLatestSensors200 = { [key: string]: SensorReading };

export type ListAlertsParams = {
  deviceId?: string;
  severity?: number;
  acknowledged?: boolean;
  limit?: number;
};

export type AcknowledgeAlert200 = {
  acknowledged: boolean;
};

export type SendCommand200 = {
  sent: boolean;
};
