/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * KAPPA Heartbeat Tracker API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AcknowledgeAlert200,
  Alert,
  CommandBody,
  DeleteDevice200,
  DeviceDetail,
  DeviceInfo,
  DeviceStats,
  GetHeartbeatHistoryParams,
  GetLatestSensors200,
  GetSensorReadingsParams,
  HealthStatus,
  HeartbeatAck,
  HeartbeatBody,
  HeartbeatRecord,
  IngestSensors200,
  IngestSensorsBody,
  KappaStatus,
  ListAlertsParams,
  ListDevicesParams,
  RegisterDeviceBody,
  SendCommand200,
  SensorReading,
} from "./api.schemas";

import { customFetch } from "../custom-fetch";
import type { ErrorType, BodyType } from "../custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns server health status
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Register or update a device
 */
export const getRegisterDeviceUrl = () => {
  return `/api/devices/register`;
};

export const registerDevice = async (
  registerDeviceBody: RegisterDeviceBody,
  options?: RequestInit,
): Promise<DeviceInfo> => {
  return customFetch<DeviceInfo>(getRegisterDeviceUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(registerDeviceBody),
  });
};

export const getRegisterDeviceMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerDevice>>,
    TError,
    { data: BodyType<RegisterDeviceBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof registerDevice>>,
  TError,
  { data: BodyType<RegisterDeviceBody> },
  TContext
> => {
  const mutationKey = ["registerDevice"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof registerDevice>>,
    { data: BodyType<RegisterDeviceBody> }
  > = (props) => {
    const { data } = props ?? {};

    return registerDevice(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegisterDeviceMutationResult = NonNullable<
  Awaited<ReturnType<typeof registerDevice>>
>;
export type RegisterDeviceMutationBody = BodyType<RegisterDeviceBody>;
export type RegisterDeviceMutationError = ErrorType<unknown>;

/**
 * @summary Register or update a device
 */
export const useRegisterDevice = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerDevice>>,
    TError,
    { data: BodyType<RegisterDeviceBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof registerDevice>>,
  TError,
  { data: BodyType<RegisterDeviceBody> },
  TContext
> => {
  return useMutation(getRegisterDeviceMutationOptions(options));
};

/**
 * @summary List all devices
 */
export const getListDevicesUrl = (params?: ListDevicesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/devices?${stringifiedParams}`
    : `/api/devices`;
};

export const listDevices = async (
  params?: ListDevicesParams,
  options?: RequestInit,
): Promise<DeviceInfo[]> => {
  return customFetch<DeviceInfo[]>(getListDevicesUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListDevicesQueryKey = (params?: ListDevicesParams) => {
  return [`/api/devices`, ...(params ? [params] : [])] as const;
};

export const getListDevicesQueryOptions = <
  TData = Awaited<ReturnType<typeof listDevices>>,
  TError = ErrorType<unknown>,
>(
  params?: ListDevicesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listDevices>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListDevicesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listDevices>>> = ({
    signal,
  }) => listDevices(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listDevices>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListDevicesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listDevices>>
>;
export type ListDevicesQueryError = ErrorType<unknown>;

/**
 * @summary List all devices
 */

export function useListDevices<
  TData = Awaited<ReturnType<typeof listDevices>>,
  TError = ErrorType<unknown>,
>(
  params?: ListDevicesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listDevices>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListDevicesQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get device statistics
 */
export const getGetDeviceStatsUrl = () => {
  return `/api/devices/stats`;
};

export const getDeviceStats = async (
  options?: RequestInit,
): Promise<DeviceStats> => {
  return customFetch<DeviceStats>(getGetDeviceStatsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetDeviceStatsQueryKey = () => {
  return [`/api/devices/stats`] as const;
};

export const getGetDeviceStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getDeviceStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getDeviceStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDeviceStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDeviceStats>>> = ({
    signal,
  }) => getDeviceStats({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDeviceStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetDeviceStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDeviceStats>>
>;
export type GetDeviceStatsQueryError = ErrorType<unknown>;

/**
 * @summary Get device statistics
 */

export function useGetDeviceStats<
  TData = Awaited<ReturnType<typeof getDeviceStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getDeviceStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetDeviceStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get device details
 */
export const getGetDeviceUrl = (deviceId: string) => {
  return `/api/devices/${deviceId}`;
};

export const getDevice = async (
  deviceId: string,
  options?: RequestInit,
): Promise<DeviceDetail> => {
  return customFetch<DeviceDetail>(getGetDeviceUrl(deviceId), {
    ...options,
    method: "GET",
  });
};

export const getGetDeviceQueryKey = (deviceId: string) => {
  return [`/api/devices/${deviceId}`] as const;
};

export const getGetDeviceQueryOptions = <
  TData = Awaited<ReturnType<typeof getDevice>>,
  TError = ErrorType<void>,
>(
  deviceId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getDevice>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDeviceQueryKey(deviceId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDevice>>> = ({
    signal,
  }) => getDevice(deviceId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!deviceId,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getDevice>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetDeviceQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDevice>>
>;
export type GetDeviceQueryError = ErrorType<void>;

/**
 * @summary Get device details
 */

export function useGetDevice<
  TData = Awaited<ReturnType<typeof getDevice>>,
  TError = ErrorType<void>,
>(
  deviceId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getDevice>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetDeviceQueryOptions(deviceId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Delete a device
 */
export const getDeleteDeviceUrl = (deviceId: string) => {
  return `/api/devices/${deviceId}`;
};

export const deleteDevice = async (
  deviceId: string,
  options?: RequestInit,
): Promise<DeleteDevice200> => {
  return customFetch<DeleteDevice200>(getDeleteDeviceUrl(deviceId), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteDeviceMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteDevice>>,
    TError,
    { deviceId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteDevice>>,
  TError,
  { deviceId: string },
  TContext
> => {
  const mutationKey = ["deleteDevice"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteDevice>>,
    { deviceId: string }
  > = (props) => {
    const { deviceId } = props ?? {};

    return deleteDevice(deviceId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteDeviceMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteDevice>>
>;

export type DeleteDeviceMutationError = ErrorType<unknown>;

/**
 * @summary Delete a device
 */
export const useDeleteDevice = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteDevice>>,
    TError,
    { deviceId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteDevice>>,
  TError,
  { deviceId: string },
  TContext
> => {
  return useMutation(getDeleteDeviceMutationOptions(options));
};

/**
 * @summary Send a heartbeat
 */
export const getSendHeartbeatUrl = () => {
  return `/api/heartbeat`;
};

export const sendHeartbeat = async (
  heartbeatBody: HeartbeatBody,
  options?: RequestInit,
): Promise<HeartbeatAck> => {
  return customFetch<HeartbeatAck>(getSendHeartbeatUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(heartbeatBody),
  });
};

export const getSendHeartbeatMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendHeartbeat>>,
    TError,
    { data: BodyType<HeartbeatBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sendHeartbeat>>,
  TError,
  { data: BodyType<HeartbeatBody> },
  TContext
> => {
  const mutationKey = ["sendHeartbeat"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sendHeartbeat>>,
    { data: BodyType<HeartbeatBody> }
  > = (props) => {
    const { data } = props ?? {};

    return sendHeartbeat(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SendHeartbeatMutationResult = NonNullable<
  Awaited<ReturnType<typeof sendHeartbeat>>
>;
export type SendHeartbeatMutationBody = BodyType<HeartbeatBody>;
export type SendHeartbeatMutationError = ErrorType<unknown>;

/**
 * @summary Send a heartbeat
 */
export const useSendHeartbeat = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendHeartbeat>>,
    TError,
    { data: BodyType<HeartbeatBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof sendHeartbeat>>,
  TError,
  { data: BodyType<HeartbeatBody> },
  TContext
> => {
  return useMutation(getSendHeartbeatMutationOptions(options));
};

/**
 * @summary Get heartbeat history
 */
export const getGetHeartbeatHistoryUrl = (
  deviceId: string,
  params?: GetHeartbeatHistoryParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/heartbeat/${deviceId}/history?${stringifiedParams}`
    : `/api/heartbeat/${deviceId}/history`;
};

export const getHeartbeatHistory = async (
  deviceId: string,
  params?: GetHeartbeatHistoryParams,
  options?: RequestInit,
): Promise<HeartbeatRecord[]> => {
  return customFetch<HeartbeatRecord[]>(
    getGetHeartbeatHistoryUrl(deviceId, params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetHeartbeatHistoryQueryKey = (
  deviceId: string,
  params?: GetHeartbeatHistoryParams,
) => {
  return [
    `/api/heartbeat/${deviceId}/history`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetHeartbeatHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getHeartbeatHistory>>,
  TError = ErrorType<unknown>,
>(
  deviceId: string,
  params?: GetHeartbeatHistoryParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getHeartbeatHistory>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetHeartbeatHistoryQueryKey(deviceId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getHeartbeatHistory>>
  > = ({ signal }) =>
    getHeartbeatHistory(deviceId, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!deviceId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getHeartbeatHistory>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetHeartbeatHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHeartbeatHistory>>
>;
export type GetHeartbeatHistoryQueryError = ErrorType<unknown>;

/**
 * @summary Get heartbeat history
 */

export function useGetHeartbeatHistory<
  TData = Awaited<ReturnType<typeof getHeartbeatHistory>>,
  TError = ErrorType<unknown>,
>(
  deviceId: string,
  params?: GetHeartbeatHistoryParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getHeartbeatHistory>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetHeartbeatHistoryQueryOptions(
    deviceId,
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Ingest sensor readings
 */
export const getIngestSensorsUrl = () => {
  return `/api/sensors`;
};

export const ingestSensors = async (
  ingestSensorsBody: IngestSensorsBody,
  options?: RequestInit,
): Promise<IngestSensors200> => {
  return customFetch<IngestSensors200>(getIngestSensorsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(ingestSensorsBody),
  });
};

export const getIngestSensorsMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof ingestSensors>>,
    TError,
    { data: BodyType<IngestSensorsBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof ingestSensors>>,
  TError,
  { data: BodyType<IngestSensorsBody> },
  TContext
> => {
  const mutationKey = ["ingestSensors"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof ingestSensors>>,
    { data: BodyType<IngestSensorsBody> }
  > = (props) => {
    const { data } = props ?? {};

    return ingestSensors(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type IngestSensorsMutationResult = NonNullable<
  Awaited<ReturnType<typeof ingestSensors>>
>;
export type IngestSensorsMutationBody = BodyType<IngestSensorsBody>;
export type IngestSensorsMutationError = ErrorType<unknown>;

/**
 * @summary Ingest sensor readings
 */
export const useIngestSensors = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof ingestSensors>>,
    TError,
    { data: BodyType<IngestSensorsBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof ingestSensors>>,
  TError,
  { data: BodyType<IngestSensorsBody> },
  TContext
> => {
  return useMutation(getIngestSensorsMutationOptions(options));
};

/**
 * @summary Get sensor readings for a device
 */
export const getGetSensorReadingsUrl = (
  deviceId: string,
  params?: GetSensorReadingsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/sensors/${deviceId}?${stringifiedParams}`
    : `/api/sensors/${deviceId}`;
};

export const getSensorReadings = async (
  deviceId: string,
  params?: GetSensorReadingsParams,
  options?: RequestInit,
): Promise<SensorReading[]> => {
  return customFetch<SensorReading[]>(
    getGetSensorReadingsUrl(deviceId, params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetSensorReadingsQueryKey = (
  deviceId: string,
  params?: GetSensorReadingsParams,
) => {
  return [`/api/sensors/${deviceId}`, ...(params ? [params] : [])] as const;
};

export const getGetSensorReadingsQueryOptions = <
  TData = Awaited<ReturnType<typeof getSensorReadings>>,
  TError = ErrorType<unknown>,
>(
  deviceId: string,
  params?: GetSensorReadingsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getSensorReadings>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetSensorReadingsQueryKey(deviceId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSensorReadings>>
  > = ({ signal }) =>
    getSensorReadings(deviceId, params, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!deviceId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getSensorReadings>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetSensorReadingsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSensorReadings>>
>;
export type GetSensorReadingsQueryError = ErrorType<unknown>;

/**
 * @summary Get sensor readings for a device
 */

export function useGetSensorReadings<
  TData = Awaited<ReturnType<typeof getSensorReadings>>,
  TError = ErrorType<unknown>,
>(
  deviceId: string,
  params?: GetSensorReadingsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getSensorReadings>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetSensorReadingsQueryOptions(
    deviceId,
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get latest sensor reading per type
 */
export const getGetLatestSensorsUrl = (deviceId: string) => {
  return `/api/sensors/${deviceId}/latest`;
};

export const getLatestSensors = async (
  deviceId: string,
  options?: RequestInit,
): Promise<GetLatestSensors200> => {
  return customFetch<GetLatestSensors200>(getGetLatestSensorsUrl(deviceId), {
    ...options,
    method: "GET",
  });
};

export const getGetLatestSensorsQueryKey = (deviceId: string) => {
  return [`/api/sensors/${deviceId}/latest`] as const;
};

export const getGetLatestSensorsQueryOptions = <
  TData = Awaited<ReturnType<typeof getLatestSensors>>,
  TError = ErrorType<unknown>,
>(
  deviceId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getLatestSensors>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetLatestSensorsQueryKey(deviceId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getLatestSensors>>
  > = ({ signal }) => getLatestSensors(deviceId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!deviceId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getLatestSensors>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetLatestSensorsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLatestSensors>>
>;
export type GetLatestSensorsQueryError = ErrorType<unknown>;

/**
 * @summary Get latest sensor reading per type
 */

export function useGetLatestSensors<
  TData = Awaited<ReturnType<typeof getLatestSensors>>,
  TError = ErrorType<unknown>,
>(
  deviceId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getLatestSensors>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetLatestSensorsQueryOptions(deviceId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List alerts
 */
export const getListAlertsUrl = (params?: ListAlertsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/alerts?${stringifiedParams}`
    : `/api/alerts`;
};

export const listAlerts = async (
  params?: ListAlertsParams,
  options?: RequestInit,
): Promise<Alert[]> => {
  return customFetch<Alert[]>(getListAlertsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListAlertsQueryKey = (params?: ListAlertsParams) => {
  return [`/api/alerts`, ...(params ? [params] : [])] as const;
};

export const getListAlertsQueryOptions = <
  TData = Awaited<ReturnType<typeof listAlerts>>,
  TError = ErrorType<unknown>,
>(
  params?: ListAlertsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listAlerts>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListAlertsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listAlerts>>> = ({
    signal,
  }) => listAlerts(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listAlerts>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListAlertsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAlerts>>
>;
export type ListAlertsQueryError = ErrorType<unknown>;

/**
 * @summary List alerts
 */

export function useListAlerts<
  TData = Awaited<ReturnType<typeof listAlerts>>,
  TError = ErrorType<unknown>,
>(
  params?: ListAlertsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listAlerts>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListAlertsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get unacknowledged alerts
 */
export const getGetActiveAlertsUrl = () => {
  return `/api/alerts/active`;
};

export const getActiveAlerts = async (
  options?: RequestInit,
): Promise<Alert[]> => {
  return customFetch<Alert[]>(getGetActiveAlertsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetActiveAlertsQueryKey = () => {
  return [`/api/alerts/active`] as const;
};

export const getGetActiveAlertsQueryOptions = <
  TData = Awaited<ReturnType<typeof getActiveAlerts>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getActiveAlerts>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetActiveAlertsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getActiveAlerts>>> = ({
    signal,
  }) => getActiveAlerts({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getActiveAlerts>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetActiveAlertsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getActiveAlerts>>
>;
export type GetActiveAlertsQueryError = ErrorType<unknown>;

/**
 * @summary Get unacknowledged alerts
 */

export function useGetActiveAlerts<
  TData = Awaited<ReturnType<typeof getActiveAlerts>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getActiveAlerts>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetActiveAlertsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Acknowledge an alert
 */
export const getAcknowledgeAlertUrl = (id: string) => {
  return `/api/alerts/${id}/acknowledge`;
};

export const acknowledgeAlert = async (
  id: string,
  options?: RequestInit,
): Promise<AcknowledgeAlert200> => {
  return customFetch<AcknowledgeAlert200>(getAcknowledgeAlertUrl(id), {
    ...options,
    method: "POST",
  });
};

export const getAcknowledgeAlertMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof acknowledgeAlert>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof acknowledgeAlert>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["acknowledgeAlert"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof acknowledgeAlert>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return acknowledgeAlert(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AcknowledgeAlertMutationResult = NonNullable<
  Awaited<ReturnType<typeof acknowledgeAlert>>
>;

export type AcknowledgeAlertMutationError = ErrorType<unknown>;

/**
 * @summary Acknowledge an alert
 */
export const useAcknowledgeAlert = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof acknowledgeAlert>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof acknowledgeAlert>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getAcknowledgeAlertMutationOptions(options));
};

/**
 * @summary Full system summary for KAPPA
 */
export const getGetKappaStatusUrl = () => {
  return `/api/kappa/status`;
};

export const getKappaStatus = async (
  options?: RequestInit,
): Promise<KappaStatus> => {
  return customFetch<KappaStatus>(getGetKappaStatusUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetKappaStatusQueryKey = () => {
  return [`/api/kappa/status`] as const;
};

export const getGetKappaStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof getKappaStatus>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getKappaStatus>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetKappaStatusQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getKappaStatus>>> = ({
    signal,
  }) => getKappaStatus({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getKappaStatus>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetKappaStatusQueryResult = NonNullable<
  Awaited<ReturnType<typeof getKappaStatus>>
>;
export type GetKappaStatusQueryError = ErrorType<unknown>;

/**
 * @summary Full system summary for KAPPA
 */

export function useGetKappaStatus<
  TData = Awaited<ReturnType<typeof getKappaStatus>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getKappaStatus>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetKappaStatusQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Send command to device via WebSocket
 */
export const getSendCommandUrl = () => {
  return `/api/kappa/command`;
};

export const sendCommand = async (
  commandBody: CommandBody,
  options?: RequestInit,
): Promise<SendCommand200> => {
  return customFetch<SendCommand200>(getSendCommandUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(commandBody),
  });
};

export const getSendCommandMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendCommand>>,
    TError,
    { data: BodyType<CommandBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sendCommand>>,
  TError,
  { data: BodyType<CommandBody> },
  TContext
> => {
  const mutationKey = ["sendCommand"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sendCommand>>,
    { data: BodyType<CommandBody> }
  > = (props) => {
    const { data } = props ?? {};

    return sendCommand(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SendCommandMutationResult = NonNullable<
  Awaited<ReturnType<typeof sendCommand>>
>;
export type SendCommandMutationBody = BodyType<CommandBody>;
export type SendCommandMutationError = ErrorType<unknown>;

/**
 * @summary Send command to device via WebSocket
 */
export const useSendCommand = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendCommand>>,
    TError,
    { data: BodyType<CommandBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof sendCommand>>,
  TError,
  { data: BodyType<CommandBody> },
  TContext
> => {
  return useMutation(getSendCommandMutationOptions(options));
};

/**
 * @summary Download PC agent script
 */
export const getGetPcAgentUrl = () => {
  return `/api/agents/pc`;
};

export const getPcAgent = async (options?: RequestInit): Promise<string> => {
  return customFetch<string>(getGetPcAgentUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetPcAgentQueryKey = () => {
  return [`/api/agents/pc`] as const;
};

export const getGetPcAgentQueryOptions = <
  TData = Awaited<ReturnType<typeof getPcAgent>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getPcAgent>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPcAgentQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPcAgent>>> = ({
    signal,
  }) => getPcAgent({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPcAgent>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetPcAgentQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPcAgent>>
>;
export type GetPcAgentQueryError = ErrorType<unknown>;

/**
 * @summary Download PC agent script
 */

export function useGetPcAgent<
  TData = Awaited<ReturnType<typeof getPcAgent>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getPcAgent>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetPcAgentQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Download phone agent script
 */
export const getGetPhoneAgentUrl = () => {
  return `/api/agents/phone`;
};

export const getPhoneAgent = async (options?: RequestInit): Promise<string> => {
  return customFetch<string>(getGetPhoneAgentUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetPhoneAgentQueryKey = () => {
  return [`/api/agents/phone`] as const;
};

export const getGetPhoneAgentQueryOptions = <
  TData = Awaited<ReturnType<typeof getPhoneAgent>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getPhoneAgent>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPhoneAgentQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPhoneAgent>>> = ({
    signal,
  }) => getPhoneAgent({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPhoneAgent>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetPhoneAgentQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPhoneAgent>>
>;
export type GetPhoneAgentQueryError = ErrorType<unknown>;

/**
 * @summary Download phone agent script
 */

export function useGetPhoneAgent<
  TData = Awaited<ReturnType<typeof getPhoneAgent>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getPhoneAgent>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetPhoneAgentQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Download bash heartbeat script
 */
export const getGetBashAgentUrl = () => {
  return `/api/agents/bash`;
};

export const getBashAgent = async (options?: RequestInit): Promise<string> => {
  return customFetch<string>(getGetBashAgentUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetBashAgentQueryKey = () => {
  return [`/api/agents/bash`] as const;
};

export const getGetBashAgentQueryOptions = <
  TData = Awaited<ReturnType<typeof getBashAgent>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getBashAgent>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBashAgentQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getBashAgent>>> = ({
    signal,
  }) => getBashAgent({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getBashAgent>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetBashAgentQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBashAgent>>
>;
export type GetBashAgentQueryError = ErrorType<unknown>;

/**
 * @summary Download bash heartbeat script
 */

export function useGetBashAgent<
  TData = Awaited<ReturnType<typeof getBashAgent>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getBashAgent>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetBashAgentQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
